// api/obfuscate.js
// POST JSON { "filename": "myscript.sh", "content": "<file text>" }
// Returns downloadable obfuscated .sh (text) with header application/x-sh

const zlib = require('zlib');

module.exports = async (req, res) => {
  if (req.method !== 'POST') {
    res.status(405).send('Method Not Allowed — use POST with JSON { filename, content }');
    return;
  }
  const body = req.body || {};
  const filename = (body.filename || 'script.sh').replace(/\s+/g, '_');
  const content = body.content;
  if (!content) {
    res.status(400).send('Missing "content" in JSON body');
    return;
  }

  try {
    const gz = zlib.gzipSync(Buffer.from(content, 'utf8'), { level: 9 });
    const b64 = gz.toString('base64');

    // Shell stub that tries to be portable:
    const stub = `#!/bin/sh
# Obfuscated shell script generated by enc-web obfuscator
# Decode & execute payload. Supports common base64/gzip variants.

_payload='${b64}'

_decode_and_exec() {
  # detect base64 decode option
  if echo x | base64 -d >/dev/null 2>&1; then
    B64CMD='base64 -d'
  elif echo x | base64 --decode >/dev/null 2>&1; then
    B64CMD='base64 --decode'
  elif echo x | base64 -D >/dev/null 2>&1; then
    B64CMD='base64 -D'
  else
    echo \"error: no base64 decode found\" >&2
    return 2
  fi

  # detect gunzip
  if command -v gzip >/dev/null 2>&1 && gzip -dc /dev/null >/dev/null 2>&1; then
    GZCMD='gzip -dc'
  elif command -v gunzip >/dev/null 2>&1; then
    GZCMD='gunzip -c'
  else
    # fallback to python3 for gzip decompress
    if command -v python3 >/dev/null 2>&1; then
      GZCMD=\"python3 -c 'import sys,gzip; sys.stdout.buffer.write(gzip.decompress(sys.stdin.buffer.read()))'\"
    else
      echo \"error: no gzip/gunzip/python3 available to decompress payload\" >&2
      return 3
    fi
  fi

  # decode, decompress, execute with /bin/sh
  echo \"Executing obfuscated payload...\"
  printf \"%s\" \"$_payload\" | eval \"$B64CMD\" | eval \"$GZCMD\" | /bin/sh \"\$@\"
  return $?
}

_decode_and_exec \"$@\"
exit $?
`;

    const outName = filename.endsWith('.sh') ? filename.replace(/\.sh$/, '.obf.sh') : filename + '.obf.sh';
    res.setHeader('Content-Type', 'application/x-sh');
    res.setHeader('Content-Disposition', `attachment; filename="${outName}"`);
    res.send(stub);

  } catch (err) {
    console.error(err);
    res.status(500).send('Server error: ' + err.message);
  }
};
